CREATE TABLE IF NOT EXISTS symptoms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symptom_key VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


INSERT INTO symptoms (symptom_key, display_name) VALUES
('stomach_pain', 'Stomach Pain'),
('acidity', 'Acidity'),
('ulcers_on_tongue', 'Ulcers On Tongue'),
('vomiting', 'Vomiting'),
('cough', 'Cough'),
('chest_pain', 'Chest Pain'),
('loss_of_appetite', 'Loss Of Appetite'),
('abdominal_pain', 'Abdominal Pain'),
('passage_of_gases', 'Passage Of Gases'),
('internal_itching', 'Internal Itching'),
('indigestion', 'Indigestion'),
('sunken_eyes', 'Sunken Eyes'),
('dehydration', 'Dehydration'),
('diarrhoea', 'Diarrhoea'),
('itching', 'Itching'),
('fatigue', 'Fatigue'),
('weight_loss', 'Weight Loss'),
('high_fever', 'High Fever'),
('yellowish_skin', 'Yellowish Skin'),
('dark_urine', 'Dark Urine'),
('lethargy', 'Lethargy'),
('yellow_urine', 'Yellow Urine'),
('yellowing_of_eyes', 'Yellowing Of Eyes'),
('malaise', 'Malaise'),
('receiving_blood_transfusion', 'Receiving Blood Transfusion'),
('receiving_unsterile_injections', 'Receiving Unsterile Injections'),
('nausea', 'Nausea'),
('family_history', 'Family History'),
('joint_pain', 'Joint Pain'),
('acute_liver_failure', 'Acute Liver Failure'),
('coma', 'Coma'),
('stomach_bleeding', 'Stomach Bleeding'),
('swelling_of_stomach', 'Swelling Of Stomach'),
('distention_of_abdomen', 'Distention Of Abdomen'),
('history_of_alcohol_consumption', 'History Of Alcohol Consumption'),
('fluid_overload', 'Fluid Overload');